# Generated by Django 4.2.6 on 2023-10-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Water',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('location', models.CharField(max_length=500)),
                ('location_url', models.URLField(unique=True)),
                ('temperature', models.FloatField()),
                ('dissolved_oxygen', models.FloatField()),
                ('faceal_content', models.FloatField()),
                ('metal_content', models.FloatField()),
                ('published', models.DateTimeField(verbose_name='published date')),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('river', models.ManyToManyField(to='water.water')),
            ],
        ),
    ]
