# Generated by Django 4.2.6 on 2023-10-05 19:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0003_remove_water_species_water_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='water',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='published date'),
        ),
    ]
