# Generated by Django 4.2.6 on 2023-10-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0004_alter_water_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='water',
            name='species',
            field=models.ManyToManyField(blank=True, null=True, to='water.species'),
        ),
    ]
