# Generated by Django 4.2.6 on 2023-10-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0006_alter_water_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='water',
            name='dissolved_oxygen',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='water',
            name='faceal_content',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='water',
            name='metal_content',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='water',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
