# Generated by Django 4.2.6 on 2023-10-07 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0007_alter_water_dissolved_oxygen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='water',
            name='water_quality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
