# Generated by Django 4.2.6 on 2023-10-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0008_water_water_quality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actvities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='water',
            name='faceal_content',
        ),
        migrations.RemoveField(
            model_name='water',
            name='metal_content',
        ),
        migrations.RemoveField(
            model_name='water',
            name='temperature',
        ),
        migrations.AddField(
            model_name='water',
            name='hightide',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='water',
            name='line1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='water',
            name='line2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='water',
            name='line3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='water',
            name='lowtide',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='water',
            name='ph',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='water',
            name='tds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='water',
            name='actvities',
            field=models.ManyToManyField(blank=True, null=True, to='water.actvities'),
        ),
    ]
