# Generated by Django 4.2.6 on 2023-10-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0009_actvities_remove_water_faceal_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='water',
            name='water_quality',
        ),
        migrations.AddField(
            model_name='water',
            name='warning',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
