# Generated by Django 4.2.6 on 2023-10-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0011_rename_actvities_water_activities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='water',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
