# Generated by Django 4.2.6 on 2023-10-08 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0012_alter_water_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Actvities',
            new_name='Activities',
        ),
    ]
